name: GADV Prototype CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  deploy:
    name: Deploy to AWS Lambda backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Installing pip requirements
        run: pip install --target ./package -r requirements.txt
      - name: Zipping pip requirements
        run: zip -r dep-pkg.zip ./package
      - name: Zipping source to create final deployment bundle
        run: zip -g dep-pkg.zip .
      - name: Deploy zip archive to Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
          handler: lambda_function.lambda_handler
          zip_file: dep-pkg.zip