name: GADV Prototype CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  deploy:
    name: Deploy to AWS Lambda backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Installing pip requirements into current directory
        run: pip install --no-cache-dir --compile -r requirements.txt --target .
      - name: Create final deployment bundle
        run: zip -qr dep-pkg.zip .
      - run: du -sh dep-pkg.zip
      - name: Deploy zip archive to Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
          handler: lambda_function.lambda_handler
          zip_file: dep-pkg.zip