name: GADV Prototype CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  deploy:
    name: Deploy to AWS Lambda backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Installing pip requirements into current directory
        run: pip install -r requirements-prod.txt --target .
      - name: Create final deployment bundle
        run: zip -qr dep-pkg.zip .
      - name: Bundle size...
        run: du -sh dep-pkg.zip
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true
      - name: Push zipped bundle to S3 Bucket
        run: aws s3 cp ./dep-pkg.zip s3://${{ secrets.AWS_S3_CODE_STORAGE_BUCKET_NAME }}/dep-pkg.zip
      - name: Update Lambda function code
        run: aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} --s3-bucket ${{ secrets.AWS_S3_CODE_STORAGE_BUCKET_NAME }} --s3-key dep-pkg.zip
